language: node_js
node_js:
  - "12"

cache:
  directories:
    - "node_modules"

dist: trusty
addons:
  chrome: stable

before_script:
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov npm test
  - nyc --reporter=lcov ng e2e --protractor-config=e2e/protractor-ci.conf.js

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
